version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - webshopstore:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=webshopdb
    # env_file:
      # - docker.env
    networks:
      - postgres
  
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8083:80" # (Host:Container)
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: webshopadmin@yopmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    # env_file:
      # - docker.env
    networks:
      - postgres

volumes:
  webshopstore:
  pgadmin-data:

networks:
  postgres:
    driver: bridge